### ISSUE TITLE
Can't annotate even though I am in project

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [diffgram/diffgram#628] opened 2022-02-18 14:27 UTC
My side:

![imagen](https://user-images.githubusercontent.com/90789402/154700919-9daef18c-08a2-422d-8e45-4740d7cf9749.png)

My coworker's side:
![WhatsApp Image 2022-02-18 at 11 26 36](https://user-images.githubusercontent.com/90789402/154701077-a1865c66-3e24-4e45-be1a-0e34004b788d.jpeg)

**Comment by vitalii-bulyzhyn** [comment] 2022-02-18 14:51
Hey @Emmanuel-Messulam ! 

The problem is your login has expired, you just need to logout and login again. We are fixing this issue in PR #590 , so it should be merged today

**Comment by MathijsNL** [comment] 2022-02-18 17:38
Also try to blur out the personal information @Emmanuel-Messulam

**Closed** 2022-02-18 17:52 UTC
