### ISSUE TITLE
Problem with aws s3 connection.

### ISSUE THREAD

**Issue by josebenitezg** [diffgram/diffgram#160] opened 2021-07-19 16:51 UTC
Hi all,

I have an issue when  I trying to connect with s3 to upload my dataset. I already have all permissions (fullS3Access). But still facing this error:

{'status_text': 'Exceeded retry limit, no valid response'}.

![cap](https://user-images.githubusercontent.com/58047828/126197122-dd73d567-a195-4ade-b30c-9b32c03f9549.png)

Would you please help me with this problem?

**Comment by PJEstrada** [comment] 2021-07-19 16:54
Hi @josebenitezg,

Thanks for using Diffgram and sharing this. Can I ask you if you could share the walrus service logs on docker compose? There might be some extra information we could use to further help you out

**Comment by josebenitezg** [comment] 2021-07-19 17:00
Yes, sure. There you go. Thank you for your fast reply.

```
walrus_1      | No module named 'shared.settings.secrets'
walrus_1      | PROCESS_MEDIA_TRY_BLOCK_ON True
walrus_1      | PROCESS_MEDIA_REMOTE_QUEUE_ON True
walrus_1      | PROCESS_MEDIA_ENQUEUE_LOCALLY_IMMEDIATELY False
walrus_1      | DIFFGRAM_SYSTEM_MODE DIFFGRAM_SYSTEM_MODE  sandbox
walrus_1      | DATABASE_URL DATABASE_URL  True
walrus_1      | [2021-07-19 16:51:17,086] INFO regular_methods.py Line 180: Starting JobLaunch Queue handler...
walrus_1      | [2021-07-19 16:51:17,086] INFO regular_methods.py Line 180: Starting SyncActionsHandlerThread Queue handler...
walrus_1      | Startup in 2.678844690322876
walrus_1      |  * Serving Flask app "Diffgram" (lazy loading)
walrus_1      |  * Environment: production
walrus_1      |    WARNING: This is a development server. Do not use it in a production deployment.
walrus_1      |    Use a production WSGI server instead.
walrus_1      |  * Debug mode: on
walrus_1      | [2021-07-19 16:51:17,087] INFO regular_methods.py Line 180: Starting DatasaurSyncManager Queue handler...
walrus_1      |  * Running on http://0.0.0.0:8082/ (Press CTRL+C to quit)
walrus_1      |  * Restarting with stat
walrus_1      | [2021-07-19 16:51:18,985] INFO regular_methods.py Line 180: Starting JobLaunch Queue handler...
walrus_1      | [2021-07-19 16:51:18,986] INFO regular_methods.py Line 180: Starting SyncActionsHandlerThread Queue handler...
walrus_1      | [2021-07-19 16:51:18,986] INFO regular_methods.py Line 180: Starting DatasaurSyncManager Queue handler...
walrus_1      |  * Debugger is active!
walrus_1      |  * Debugger PIN: 216-466-502
walrus_1      | [2021-07-19 16:51:41,971] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:51:43,932] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:51:48] "POST /api/walrus/v1/project/ambev-br/input/view/list HTTP/1.1" 200 -
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:51:57] "POST /api/walrus/v1/project/ambev-br/input/update HTTP/1.1" 200 -
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:51:57] "POST /api/walrus/v1/project/ambev-br/input/view/list HTTP/1.1" 200 -
walrus_1      | [2021-07-19 16:52:00,124] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]43
walrus_1      | [2021-07-19 16:52:13,132] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]13
walrus_1      | [2021-07-19 16:52:16,771] INFO process_media.py Line 1813: 39 InputID Probably Downloaded
walrus_1      | [2021-07-19 16:52:16,894] INFO event.py Line 309: Sent event: 100 to Diffgram Eventhub
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:52:16] "POST /api/walrus/project/ambev-br/upload/large HTTP/1.1" 200 -
walrus_1      | [2021-07-19 16:52:17,128] INFO event.py Line 309: Sent event: 101 to Diffgram Eventhub
walrus_1      | [2021-07-19 16:52:17,257] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:52:19,189] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:52:27,134] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]14
walrus_1      | [2021-07-19 16:52:54,062] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]95
walrus_1      | [2021-07-19 16:53:07,077] INFO regular_methods.py Line 184: [Job Launch Queue heartbeat]108
walrus_1      | [2021-07-19 16:53:13,182] INFO regular_methods.py Line 184: [Job Launch Queue heartbeat]116
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:53:18] "POST /api/walrus/v1/project/ambev-br/input/view/list HTTP/1.1" 200 -
walrus_1      | [2021-07-19 16:53:22,327] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:53:24,257] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:54:11,208] INFO regular_methods.py Line 184: [Job Launch Queue heartbeat]58
walrus_1      | [2021-07-19 16:54:14,214] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]107
walrus_1      | [2021-07-19 16:54:18,139] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]84
walrus_1      | [2021-07-19 16:54:21,143] INFO regular_methods.py Line 184: [Job Launch Queue heartbeat]74
walrus_1      | [2021-07-19 16:54:26,227] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]12
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:54:34] "POST /api/walrus/v1/connectors/5/fetch-data HTTP/1.1" 200 -
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:54:35] "POST /api/walrus/v1/connectors/5/fetch-data HTTP/1.1" 200 -
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:54:39] "POST /api/walrus/v1/connectors/5/fetch-data HTTP/1.1" 200 -
walrus_1      | 172.18.0.6 - - [19/Jul/2021 16:54:49] "POST /api/walrus/v1/connectors/5/fetch-data HTTP/1.1" 200 -
walrus_1      | [2021-07-19 16:54:49,242] INFO event.py Line 309: Sent event: 102 to Diffgram Eventhub
walrus_1      | [2021-07-19 16:54:57,414] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-19 16:54:57,420] INFO process_media.py Line 158: 40 Added to queue.
walrus_1      | comit...
walrus_1      | [2021-07-19 16:54:57,502] ERROR process_media.py Line 1874: Exceeded retry limit, no valid response
walrus_1      | [2021-07-19 16:54:57,503] INFO process_media.py Line 1813: 40 InputID Probably Downloaded
walrus_1      | {'status_text': 'Exceeded retry limit, no valid response'}
walrus_1      | [2021-07-19 16:54:57,504] ERROR process_media.py Line 500: {'status_text': 'Exceeded retry limit, no valid response'}
```

**Comment by PJEstrada** [comment] 2021-07-19 17:39
Thanks for sharing the logs :) 

The problem seem to me to be either a permission with that bucket specifically when downloading the generated signed URL.

We are going to work on improving the error messages to give more information about the missing permissions in the next releases of Diffgram.

For now to debug your issue, could you please try generating a signed URL, and then accessing it with your S3 client? 

It seems that the problem is related to that .

A way to do it with Python and boto3 is

```
client = boto3.client('s3', aws_access_key_id=your_id, aws_secret_access_key=your_secret)
signed_url = client.generate_presigned_url('get_object', 
            Params={'Bucket': ,<YOUR BUCKET NAME>,'Key': <YOUR OBJECT PATH>},
            ExpiresIn=3600 * 24 * 6)  # 5 Days.


```

Check if you are getting any permissions error both to generate the signed URL and to access the URL. 

It could also help if you could double check if that fullS3Access roles is correctly attached to the Access Key you added in Diffgram. You can share the policy here to to further debug.

**Comment by josebenitezg** [comment] 2021-07-19 19:01
I don't get any errors. I am able to generate the signed URL successfully.
I also double check the Access key have the fulls3Access
![Captura de Pantalla 2021-07-19 a la(s) 15 58 23](https://user-images.githubusercontent.com/58047828/126212868-5984cc93-224e-44dd-ab62-e094affcb4d3.png)

**Comment by PJEstrada** [comment] 2021-07-19 19:10
> I don't get any errors. I am able to generate the signed URL successfully.
> I also double check the Access key have the fulls3Access
> ![Captura de Pantalla 2021-07-19 a la(s) 15 58 23](https://user-images.githubusercontent.com/58047828/126212868-5984cc93-224e-44dd-ab62-e094affcb4d3.png)

If you visit the URL are you able to acess the content?

**Comment by josebenitezg** [comment] 2021-07-19 19:14
> > I don't get any errors. I am able to generate the signed URL successfully.
> > I also double check the Access key have the fulls3Access
> > ![Captura de Pantalla 2021-07-19 a la(s) 15 58 23](https://user-images.githubusercontent.com/58047828/126212868-5984cc93-224e-44dd-ab62-e094affcb4d3.png)
> 
> If you visit the URL are you able to acess the content?

![Captura de Pantalla 2021-07-19 a la(s) 16 13 57](https://user-images.githubusercontent.com/58047828/126214406-97569833-b88c-423d-b458-f62f2eb1e4c7.png)

This could be a problem right?

**Comment by PJEstrada** [comment] 2021-07-19 19:19
> > > I don't get any errors. I am able to generate the signed URL successfully.
> > > I also double check the Access key have the fulls3Access
> > > ![Captura de Pantalla 2021-07-19 a la(s) 15 58 23](https://user-images.githubusercontent.com/58047828/126212868-5984cc93-224e-44dd-ab62-e094affcb4d3.png)
> > 
> > 
> > If you visit the URL are you able to acess the content?
> 
> ![Captura de Pantalla 2021-07-19 a la(s) 16 13 57](https://user-images.githubusercontent.com/58047828/126214406-97569833-b88c-423d-b458-f62f2eb1e4c7.png)
> 
> This could be a problem right?

Yes, that is most likely the issue. Can you test with another bucker or region in your AWS account?

**Comment by josebenitezg** [comment] 2021-07-19 19:46
So, now apparently work because I have success to upload the images. But I face a new problem jajaja. I don't why the images do not show.
<img width="1396" alt="Captura de Pantalla 2021-07-19 a la(s) 16 41 36" src="https://user-images.githubusercontent.com/58047828/126217758-f96a404a-47dd-433f-aded-5a8a85d76055.png">

<img width="1410" alt="Captura de Pantalla 2021-07-19 a la(s) 16 41 46" src="https://user-images.githubusercontent.com/58047828/126217789-7db6850b-81e3-48b0-9902-4c631f5909bc.png">

This error show me even if I upload the images from my computer.

**Comment by PJEstrada** [comment] 2021-07-19 19:50
> So, now apparently work because I have success to upload the images after change the s3 properties. But I face a new problem jajaja. I don't why the images do not show.
> <img alt="Captura de Pantalla 2021-07-19 a la(s) 16 41 36" width="1396" src="https://user-images.githubusercontent.com/58047828/126217758-f96a404a-47dd-433f-aded-5a8a85d76055.png">
> 
> <img alt="Captura de Pantalla 2021-07-19 a la(s) 16 41 46" width="1410" src="https://user-images.githubusercontent.com/58047828/126217789-7db6850b-81e3-48b0-9902-4c631f5909bc.png">
> 
> This error show me even if I upload the images from my computer.

Thanks for the info @josebenitezg. Can you please check on your network tab in the explorer if the image fetching is throwing an error and share that with us? I suspect that URL will have the same problem you showed above.

**Comment by josebenitezg** [comment] 2021-07-19 20:25
So, I was able to finde the solution. The main problem was that the first configuration of aws was with other bucket that hasn't the same permission as the new one that I've created.
Now everything looks fine. I'll try to upload a big dataset to annotate (300k images).
That number of dataset shouldn't be a problem right?

Thank you for your help @PJEstrada !

**Comment by josebenitezg** [comment] 2021-07-19 20:27
sorry I close the issue for error

**Comment by PJEstrada** [comment] 2021-07-19 22:41
Hey @josebenitezg  glad you got it working :)

Diffgram should be able to handle large datasets, other users had been able to upload multi GB videos and we recently uploaded the 120K images COCO dataset.

The only consideration here is processing time, which is mostly given by the amount of workers and the machine specs:

Here's a bit more information on the topic:
https://diffgram.readme.io/docs/file-processing-performances

Let me know if this helps you and we can close the issue

**Comment by josebenitezg** [comment] 2021-07-20 02:56
Hi @PJEstrada We are trying to upload aprox 17k images from s3, now we are able to do it but we are facing another problem.

It seems that we have 999+ object in the bucket and when we import the data only upload the first 999 objects which is the first page on s3.

<img width="1099" alt="Captura de Pantalla 2021-07-19 a la(s) 23 52 38" src="https://user-images.githubusercontent.com/58047828/126254774-f788adf5-d5c3-41a5-8f42-2b9073bcc99f.png">

<img width="1437" alt="Captura de Pantalla 2021-07-19 a la(s) 23 53 10" src="https://user-images.githubusercontent.com/58047828/126254853-e0313987-0a22-445e-9036-e0ca652b405d.png">

**Comment by PJEstrada** [comment] 2021-07-20 03:26
> Hi @PJEstrada We are trying to upload aprox 17k images from s3, now we are able to do it but we are facing another problem.
> 
> It seems that we have 999+ object in the bucket and when we import the data only upload the first 999 objects which is the first page on s3.
> 
> <img alt="Captura de Pantalla 2021-07-19 a la(s) 23 52 38" width="1099" src="https://user-images.githubusercontent.com/58047828/126254774-f788adf5-d5c3-41a5-8f42-2b9073bcc99f.png">
> 
> <img alt="Captura de Pantalla 2021-07-19 a la(s) 23 53 10" width="1437" src="https://user-images.githubusercontent.com/58047828/126254853-e0313987-0a22-445e-9036-e0ca652b405d.png">

Hello @josebenitezg, thanks for sharing this one. You're right, for now we still don't yet support pagination at the UI level, but if you just select the entire `batch_1/` folder, it should fetch all the items on the folder regardless of not showing them on the UI. 

We will add a separate issue to support pagination on the file browser for really large folders on the UI.

Let me know if this works for you!

**Comment by josebenitezg** [comment] 2021-07-20 12:41
The problem is that we have a json inside this batch_1 and it seems that not read because show the error 'load a csv o json file' but I solve this renaming the json file in order to show in the first pagination and that's apparently work. But when I setup the json I have problem in this step:

<img width="1403" alt="Captura de Pantalla 2021-07-20 a la(s) 09 38 07" src="https://user-images.githubusercontent.com/58047828/126325443-290be20b-dbe3-43f6-a5d1-bda9773f137f.png">

This file exist in my bucket!

json format:
```
[
    {
        "file_name": "00abcf45-570e-4250-aeb1-0918d2b6f2d4_cam1_id37_IN2-SP-03.jpg",
        "type": "box",
        "label_name": "red_bull_250",
        "lower_x": 77.0,
        "upper_x": 156.0,
        "lower_y": 334.0,
        "upper_y": 204.0
    },
.
.
.
]
```

**Comment by PJEstrada** [comment] 2021-07-20 14:00
I see,

Since you're trying a big upload of images and we currently don't support pagination to add all the specific file names at the UI level, we would suggest you try uploading this using the Diffgram Python SDK:

**Comment by josebenitezg** [comment] 2021-07-20 14:05
Thi

> I see,
> 
> Since you're trying a big upload of images and we currently don't support pagination to add all the specific file names at the UI level, we would suggest you try uploading this using the [Diffgram Python SDK:](https://github.com/diffgram/python-sdk)
> 
> You would have 2 routes to go here:

Is this also impact on the json file? I mean, the json file only read the first object in the bucket but the second can't find it.

**Comment by PJEstrada** [comment] 2021-07-20 14:13
> I'm sorry, the comment was cuttted offf, and I did not finish writing it all:
> 
> Since you're trying a big upload of images and we currently don't support pagination to add all the specific file names at the UI level, we would suggest you try uploading this using the [Diffgram Python SDK:](https://github.com/diffgram/python-sdk)
> 
> You could try the following
> 
> 1. Upload all the files with Directly from the SDK using something like this:
> 
> ```
> def mock_box_from_external_format(
>             sequence_number: int = None,
>             name : str = None):
> 
>     return {
>         "name" : name,
>         "number": sequence_number,
>         "type": "box",
>         "x_max": random.randint(500, 800),
>         "x_min": random.randint(400, 499),
>         "y_max": random.randint(500, 800),
>         "y_min": random.randint(400, 499)
>         }
> def test_existing_instances_image(project):
> 
>     signed_url = "https://storage.googleapis.com/diffgram_public/example_data/000000001323.jpg"
> 
>     # This part you could read from your existing JSON to build the instance_list
>     instance_list = []
> 
>     for i in range(3):
>         instance_list.append(
>            mock_box_from_external_format(name = "cat"))
> 
>     result = project.file.from_url(
>         signed_url,
>         media_type="image",
>         instance_list=instance_list
>     )
> ```
> 
> For more information on uploading/updating existing files from the SDK you can read this: https://diffgram.readme.io/docs/importing-instances-walkthrough
> 
> https://diffgram.readme.io/docs/files#fileupdate
> 
> You can access your diffgram project with:
> 
> ```
> from diffgram import Project
> 
> 
> project = Project(host = "URL_TO_YOUR_HOSTED_DIFFGRAM",
> 		  project_string_id = "replace_with_project_string",
> 		  client_id = "replace_with_client_id",
> 		  client_secret = "replace_with_client_secret")
> ```
> 
> I have created a separete issue to track the pagination issue at the UI level here: #161

@josebenitezg  I accidentally posted the comment without finishing it. I've added a bit more info now :)

**Comment by josebenitezg** [comment] 2021-07-20 15:06
I really appreciate your help @PJEstrada. I'll try to upload the images with annotations trough the SDK and I'll let you know if everything goes well.
Thank you!!!

**Comment by PJEstrada** [comment] 2021-07-20 15:30
Sounds good @josebenitezg  glad I could help a bit! Let me know if you have any other questions.

**Comment by josebenitezg** [comment] 2021-07-21 15:43
Hi @PJEstrada!

So we are trying to upload the images through the SDK. Apparently everything works fine but we found like an issue (or not jaja)
When the batch start we create a dataset with `project.directory.new(batch_name)` and then set the dataset in the current batch with `project.set_directory_by_name(batch_name)`. The upload is working fine but the dataset only set with batch_1. For the images in batch_2 and the rest of batches are set with default dataset.

This is part of my code:
```
for batch in range(1,21):

    project = Project(host = "http://XXX", project_string_id = "XXX", client_id = "XXX", client_secret = "XXX") 

    batch_name = 'Batch_{}'.format(batch)
    #if dataset already exist then just set by name
    try:
        print('[INFO] Creating new directory. Name: Batch_{}'.format(batch))
        project.directory.new(batch_name)
    except:
        print('[INFO] Dataset is already created')
    
    time.sleep(1)

    print('[INFO] Setting batch_{} to the project'.format(batch))
    project.set_directory_by_name(batch_name)

    time.sleep(1)

    print('[INFO] Getting list of objects (images from s3 bucket)')
    prefix_name = 'batch_{}/'.format(batch)
    file_list = ListFilesV1(client, _BUCKET_NAME, prefix=prefix_name)
    
    print('[INFO] Processing batch_{} images'.format(batch))

    for file in tqdm(file_list):
        image = file.split('/')[-1]
        instance_list = not_skipped_images_annotations.get(image)
        if instance_list is None:
            instance_list = []    
        signed_url = get_signed_url(file)
        result = project.file.from_url(signed_url, media_type='image', instance_list=instance_list) 
```
We already uploaded 200k approximately but with this issue

**Comment by PJEstrada** [comment] 2021-07-21 15:56
> project.file.from_url

Hi @josebenitezg,

Glad you're already uploading! Could you try moving the line:

`    project = Project(host = "http://XXX", project_string_id = "XXX", client_id = "XXX", client_secret = "XXX") `

Out of the for loop? I'm guessing this might be resettting some metadata each time. 

Also, does the `project.set_directory_by_name(batch_name)` throws any error/warning?

Let me know if this works for you

**Comment by josebenitezg** [comment] 2021-07-21 16:02
I already move that line outside. Actually I move it inside because I thought that the problem could be that the project functions is outside. But i face the same problem.

Not, It doesn't show me any error.

Can we access to the postgresql dataset and change the dataset for the images?

**Comment by PJEstrada** [comment] 2021-07-21 16:13
No worries @josebenitezg  thanks for the info on that.

You can change the dataset from the UI by going to the data explorer section:

![image](https://user-images.githubusercontent.com/6606958/126522548-1921b2d7-8ee9-454f-9218-575eb83eca36.png)

More info: https://diffgram.readme.io/docs/moving-files


For the code issue:

Could you try doing:

`dir = project.directory.get(batch_name)`

and then 
`project.set_default_directory(directory_id = dir.id)`?

**Comment by anthony-sarkis** [comment] 2021-07-21 19:17
@josebenitezg  

Sorry we had a bug in the SDK that's been fixed here: https://github.com/diffgram/python-sdk/pull/3

Please `pip install diffgram --upgrade` to 0.3.4 and try again? Please confirm if fixed or not?

Best
Anthony

**Comment by josebenitezg** [comment] 2021-07-23 13:29
Hi Anthony, thank your for solving the bug. We'll try next time we upload data. It was faster for us to access postgresql and move the files from one dataset to another because the amount of images.

But I'll make sure to let you know when we upload again.

**Comment by anthony-sarkis** [comment] 2021-07-23 14:06
Pleasure! Ok sounds good,
All the best,
Anthony

**Comment by PJEstrada** [comment] 2021-07-23 14:20
I'm closing this issue for now, please feel free to open a new one if you have any questions, suggestions or feedback!

**Closed by PJEstrada** 2021-07-23 14:20 UTC
Labels: admin experience, blob-storage-layer, installation, s3

**Comment by cvm-int** [comment] 2021-07-23 15:30
Dear PJEstrada, 

I am part of josebentizg team and while importing 200k images,  the process stopped with the following log error on the Walrus service.

![image](https://user-images.githubusercontent.com/73854485/126805273-a6710dfc-40bd-4fdf-8a45-a870fa9391d3.png)

```
Attaching to diffgram_walrus_1
walrus_1      | Exception in thread Thread-83199:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
walrus_1      | 
walrus_1      | Exception in thread Thread-88477:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)

```

**Comment by PJEstrada** [comment] 2021-07-23 15:46
Hi @cvm-int,

I've moved this to a separate issue since to keep the context of each problem separate,

https://github.com/diffgram/diffgram/issues/171
